### PR TITLE
added error messages some rule classes

### PR DESCRIPTION
**Pull request by emrekose26**
Hi, @wajahatkarim3 I've added error messages to some classes what you want. If it okay, I will add error messages in other classes with next PR.

### CODE REVIEW

**Comment by wajahatkarim3** [comment]
Thank you @emrekose26 
I have one question though. Why is there ```@StringRes``` annotation? Does that mean that constructor will only accept String from resources or any other string can also work on it? 
Good work man

**Comment by emrekose26** [comment]
There is `@StringRes` annotation. Because error messages can both any string resources or any string value what you want. 
So, should I remove this annotation?

**Comment by antercepter** [comment]
I'm sorry, but I started this task as well. @StringRes is using wrong in this PR, only `int` values should have this annotation, please read the [docs](https://developer.android.com/reference/android/support/annotation/StringRes)

**Comment by wajahatkarim3** [comment]
@emrekose26 since resources need a ```Context``` object, so we should only accept ```String``` as error messages. If anyone wants yo fetch it from resources, he can do it by giving us final ```String``` messages. 
So please remove the annotation and put plain string.

**Comment by wajahatkarim3** [comment]
@antercepter I am sorry that I re-assigned this issue to @emrekose26. Let him do it. I will post some more issues today. If you are interested, you can start any of those as well. 
Thank you for your interest and contributions :smiley:

**Comment by emrekose26** [comment]
@wajahatkarim3 Okay. I will remove that annotation
@antercepter There are a lot of classes that are supposed to add error message. We work together if you want. For example, I can change half of them and you can change the rest of them. What do you think?

**Comment by antercepter** [comment]
@emrekose26 Do it, if you started already, because there may be conflicts and it will take more time to fix them than work alone :) I'll find other issue. Good luck!

**Comment by emrekose26** [comment]
@wajahatkarim3 I closed this PR. Because I created a new one.

**Pull request closed without merging**
